spring:
  application:
    name: farm
  datasource:
    url: jdbc:postgresql://localhost:5432/FarmManagement
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  web:
    locale: ro
    locale-resolver: fixed

  sql:
    init:
      mode: always          # always | embedded | never
      platform: postgres   # important for picking postgres scripts
      continue-on-error: false
      encoding: UTF-8